server:
  allow_cors: false
  http:
    port: 8080
  grpc:
    port: 9092
  limit:
    enabled: true
    period: 86400
chains:
  - name: "orai"
    chain_id: "testing"
    rpc_endpoint: "http://localhost:26657/"
    account_prefix: "orai"
    key: "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
    gas_adjustment: 2
    gas_price: "0.1orai"
    drop_coin: "10000000orai"
