server:
  allow_cors: false
  http:
    port: 8080
  grpc:
    port: 9092
  limit:
    enabled: true
    period: 86400
chains:
  - name: "orai"
    chain_id: "Oraichain-testnet"
    rpc_endpoint: "https://testnet-v2.rpc.orai.io:443/"
    account_prefix: "orai"
    key: "fault actress void dress era ecology barrel recycle motor tennis volcano ridge road bone endless tree today cheese brief dawn feature girl resemble must"
    gas_adjustment: 2.5
    gas_price: "0.1orai"
    drop_coin: "5000000orai"
    drop_max_coin:  "1000000000000factory/orai1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjqtsu49d/max"