name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Deploy to k8s
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: oraichain/cosmfaucet
          tags: |
            type=sha,enable=true,priority=100,prefix=dev-,suffix=,format=short

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          cache-from: type=registry,ref=oraichain/cosmfaucet:buildcache
          cache-to: type=registry,ref=oraichain/cosmfaucet:buildcache,mode=max
          platforms: linux/amd64

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: oraichain/infra-deployments
          event-type: image-tag
          client-payload: '{"chart_name": "cosmfaucet", "tag": "${{ env.DOCKER_METADATA_OUTPUT_VERSION }}", "target": "staging", "env": "staging"}'